
site_name: STA:CCC
theme:
  name: material
  custom_dir: 'yaml-wiki/theme'
  palette:
    primary: blue
    accent: blue
  favicon: 'img/favicon.ico'
  icon:
    logo: 'material/compass'
repo_name: 'tapanther/STA-CCC'
repo_url: 'https://github.com/tapanther/STA-CCC'
site_url: 'https://tapanther.github.io/STA-CCC/'

index_tag_text: >-
    Welcome to the STA:CCC Player's Wiki!


    This site contains canon, in-universe information for the game. The information on this site takes precedence over
    [Memory Alpha](https://memory-alpha.fandom.com/) or [Memory Beta](https://memory-beta.fandom.com/).


    Some pages may contain only links to these sites, in which case there is no game-specific information at this time.
    Others may not have either link, in which case the information on those sites should be considered non-canon for
    the purposes of the game.


    The entirety of `Star Trek: Enterprise` is considered canon, but information from future series should not be
    taken as fully canon, as the older series often have contradictory information about this time period of human
    history.

  
extra_css:
  - stylesheets_lib/uml.css
  
extra_javascript:
  - js_lib/uml.js
  - js_lib/mermaid.min.js
#  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.4.6/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.9.1/underscore-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.13.0/flowchart.min.js

markdown_extensions:
  - admonition
  - pymdownx.superfences :
      custom_fences :
        - name : flow
          class : uml-flowchart
          format : !!python/name:pymdownx.superfences.fence_div_format
        - name : sequence
          class : uml-sequence-diagram
          format : !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

nav:
  - Home : index.md
  - Denobula :
    - Denobula : DenobulaPlanet.md
    - Denobulan Civilization : DenobulaCiv.md
  - General :
    - Timeline : Timeline.md
  - Other :
    - Systems :
      - Galorndon Core :
        - Galorndon Core : GalorndonCore.md
  - Romulan Star Empire :
    - Romulan Star Empire : RomulanStarEmpire.md
  - United Earth :
    - Starfleet Command : StarfleetCommand.md
    - United Earth : UnitedEarth.md
    - United Earth Space Probe Agency : UESPA.md
    - History :
      - Fleet Modernization Program : FleetModernization.md
    - NPC :
      - Admiral Rafael Douglas : AdmiralDouglas.md
    - Vessels :
      - Endeavour (NX-06) : Endeavour.md
      - SS Nightingale (UES 9016) : Nightingale.md
  - Vulcan :
    - Vulcan High Council : VulcanHighCouncil.md
    - Vulcan Space Agency : VulcanSpaceAgency.md
  - Categories :
      - Denobula : Denobula.md
      - General : General.md
      - Other : Other.md
      - Romulan Star Empire : Romulan Star Empire.md
      - United Earth : United Earth.md
      - Vulcan : Vulcan.md
