
site_name: STA:CCC
theme:
  name: material
  custom_dir: 'yaml-wiki/theme'
  palette:
    primary: blue
    accent: blue
  favicon: 'img/favicon.ico'
  icon:
    logo: 'material/compass'
repo_name: 'tapanther/STA-CCC'
repo_url: 'https://github.com/tapanther/STA-CCC'
site_url: 'https://tapanther.github.io/STA-CCC/'

  
extra_css:
  - stylesheets_lib/uml.css
  
extra_javascript:
  - js_lib/uml.js
  - js_lib/mermaid.min.js
#  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.4.6/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.9.1/underscore-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.13.0/flowchart.min.js

markdown_extensions:
  - admonition
  - pymdownx.superfences :
      custom_fences :
        - name : flow
          class : uml-flowchart
          format : !!python/name:pymdownx.superfences.fence_div_format
        - name : sequence
          class : uml-sequence-diagram
          format : !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

nav:
  - Home : index.md
  - General :
    - Timeline : Timeline.md
  - Locations :
    - Systems :
      - Galorndon Core :
        - Galorndon Core : GalorndonCore.md
  - Major Powers :
    - Romulan Star Empire :
      - Romulan Star Empire : RomulanStarEmpire.md
  - NPC :
    - Starfleet :
      - Admiral Rafael Douglas : AdmiralDouglas.md
  - Vessels :
    - Starfleet :
      - Endeavour (NX-06) : Endeavour.md
      - SS Nightingale (UES 9016) : Nightingale.md
  - Categories :
      - General : General.md
      - Locations : Locations.md
      - Major Powers : Major Powers.md
      - NPC : NPC.md
      - Vessels : Vessels.md
